// 食材数据库 - 常见冰箱食材及多语言翻译
const INGREDIENTS_DB = [
  // 蔬菜类
  { id: 'carrot', name: '胡萝卜', category: 'vegetable', categoryName: '蔬菜', icon: '🥕', defaultUnit: '根', defaultShelfDays: 14, translations: { en: { name: 'Carrot', phonetic: '/ˈkær.ət/' }, ja: { name: 'にんじん', phonetic: 'ニンジン (ninjin)' }, ko: { name: '당근', phonetic: '당근 (danggeun)' }, fr: { name: 'Carotte', phonetic: '/ka.ʁɔt/' }, es: { name: 'Zanahoria', phonetic: '/θa.na.ˈo.ɾja/' }, de: { name: 'Karotte', phonetic: '/ka.ˈʁɔ.tə/' } } },
  { id: 'tomato', name: '番茄', category: 'vegetable', categoryName: '蔬菜', icon: '🍅', defaultUnit: '个', defaultShelfDays: 7, translations: { en: { name: 'Tomato', phonetic: '/təˈmeɪ.toʊ/' }, ja: { name: 'トマト', phonetic: 'トマト (tomato)' }, ko: { name: '토마토', phonetic: '토마토 (tomato)' }, fr: { name: 'Tomate', phonetic: '/tɔ.mat/' }, es: { name: 'Tomate', phonetic: '/to.ˈma.te/' }, de: { name: 'Tomate', phonetic: '/to.ˈmaː.tə/' } } },
  { id: 'cucumber', name: '黄瓜', category: 'vegetable', categoryName: '蔬菜', icon: '🥒', defaultUnit: '根', defaultShelfDays: 7, translations: { en: { name: 'Cucumber', phonetic: '/ˈkjuː.kʌm.bər/' }, ja: { name: 'きゅうり', phonetic: 'キュウリ (kyūri)' }, ko: { name: '오이', phonetic: '오이 (o-i)' }, fr: { name: 'Concombre', phonetic: '/kɔ̃.kɔ̃bʁ/' }, es: { name: 'Pepino', phonetic: '/pe.ˈpi.no/' }, de: { name: 'Gurke', phonetic: '/ˈɡʊʁ.kə/' } } },
  { id: 'cabbage', name: '白菜', category: 'vegetable', categoryName: '蔬菜', icon: '🥬', defaultUnit: '棵', defaultShelfDays: 10, translations: { en: { name: 'Cabbage', phonetic: '/ˈkæb.ɪdʒ/' }, ja: { name: 'はくさい', phonetic: 'ハクサイ (hakusai)' }, ko: { name: '배추', phonetic: '배추 (baechu)' }, fr: { name: 'Chou', phonetic: '/ʃu/' }, es: { name: 'Col', phonetic: '/kol/' }, de: { name: 'Kohl', phonetic: '/koːl/' } } },
  { id: 'potato', name: '土豆', category: 'vegetable', categoryName: '蔬菜', icon: '🥔', defaultUnit: '个', defaultShelfDays: 21, translations: { en: { name: 'Potato', phonetic: '/pəˈteɪ.toʊ/' }, ja: { name: 'じゃがいも', phonetic: 'ジャガイモ (jagaimo)' }, ko: { name: '감자', phonetic: '감자 (gamja)' }, fr: { name: 'Pomme de terre', phonetic: '/pɔm də tɛʁ/' }, es: { name: 'Patata', phonetic: '/pa.ˈta.ta/' }, de: { name: 'Kartoffel', phonetic: '/kaʁˈtɔ.fəl/' } } },
  { id: 'onion', name: '洋葱', category: 'vegetable', categoryName: '蔬菜', icon: '🧅', defaultUnit: '个', defaultShelfDays: 30, translations: { en: { name: 'Onion', phonetic: '/ˈʌn.jən/' }, ja: { name: 'たまねぎ', phonetic: 'タマネギ (tamanegi)' }, ko: { name: '양파', phonetic: '양파 (yangpa)' }, fr: { name: 'Oignon', phonetic: '/ɔ.ɲɔ̃/' }, es: { name: 'Cebolla', phonetic: '/θe.ˈβo.ʎa/' }, de: { name: 'Zwiebel', phonetic: '/ˈtsvíː.bəl/' } } },
  { id: 'garlic', name: '大蒜', category: 'vegetable', categoryName: '蔬菜', icon: '🧄', defaultUnit: '头', defaultShelfDays: 30, translations: { en: { name: 'Garlic', phonetic: '/ˈɡɑːr.lɪk/' }, ja: { name: 'にんにく', phonetic: 'ニンニク (ninniku)' }, ko: { name: '마늘', phonetic: '마늘 (maneul)' }, fr: { name: 'Ail', phonetic: '/aj/' }, es: { name: 'Ajo', phonetic: '/ˈa.xo/' }, de: { name: 'Knoblauch', phonetic: '/ˈknoːp.laʊx/' } } },
  { id: 'broccoli', name: '西兰花', category: 'vegetable', categoryName: '蔬菜', icon: '🥦', defaultUnit: '棵', defaultShelfDays: 5, translations: { en: { name: 'Broccoli', phonetic: '/ˈbrɒk.ə.li/' }, ja: { name: 'ブロッコリー', phonetic: 'ブロッコリー (burokkorī)' }, ko: { name: '브로콜리', phonetic: '브로콜리 (beurokoli)' }, fr: { name: 'Brocoli', phonetic: '/bʁɔ.kɔ.li/' }, es: { name: 'Brócoli', phonetic: '/ˈbɾo.ko.li/' }, de: { name: 'Brokkoli', phonetic: '/ˈbʁɔ.ko.liː/' } } },
  { id: 'eggplant', name: '茄子', category: 'vegetable', categoryName: '蔬菜', icon: '🍆', defaultUnit: '个', defaultShelfDays: 7, translations: { en: { name: 'Eggplant', phonetic: '/ˈeɡ.plænt/' }, ja: { name: 'なす', phonetic: 'ナス (nasu)' }, ko: { name: '가지', phonetic: '가지 (gaji)' }, fr: { name: 'Aubergine', phonetic: '/o.bɛʁ.ʒin/' }, es: { name: 'Berenjena', phonetic: '/be.ɾen.ˈxe.na/' }, de: { name: 'Aubergine', phonetic: '/o.bɛʁ.ˈʒiː.nə/' } } },
  { id: 'corn', name: '玉米', category: 'vegetable', categoryName: '蔬菜', icon: '🌽', defaultUnit: '根', defaultShelfDays: 5, translations: { en: { name: 'Corn', phonetic: '/kɔːrn/' }, ja: { name: 'とうもろこし', phonetic: 'トウモロコシ (tōmorokoshi)' }, ko: { name: '옥수수', phonetic: '옥수수 (oksusu)' }, fr: { name: 'Maïs', phonetic: '/ma.is/' }, es: { name: 'Maíz', phonetic: '/ma.ˈiθ/' }, de: { name: 'Mais', phonetic: '/maɪs/' } } },
  { id: 'bellpepper', name: '青椒', category: 'vegetable', categoryName: '蔬菜', icon: '🫑', defaultUnit: '个', defaultShelfDays: 7, translations: { en: { name: 'Bell Pepper', phonetic: '/bɛl ˈpɛp.ər/' }, ja: { name: 'ピーマン', phonetic: 'ピーマン (pīman)' }, ko: { name: '피망', phonetic: '피망 (pimang)' }, fr: { name: 'Poivron', phonetic: '/pwa.vʁɔ̃/' }, es: { name: 'Pimiento', phonetic: '/pi.ˈmjɛn.to/' }, de: { name: 'Paprika', phonetic: '/ˈpaːp.ʁiː.ka/' } } },
  { id: 'spinach', name: '菠菜', category: 'vegetable', categoryName: '蔬菜', icon: '🥬', defaultUnit: '把', defaultShelfDays: 4, translations: { en: { name: 'Spinach', phonetic: '/ˈspɪn.ɪtʃ/' }, ja: { name: 'ほうれんそう', phonetic: 'ホウレンソウ (hōrensō)' }, ko: { name: '시금치', phonetic: '시금치 (sigeumchi)' }, fr: { name: 'Épinard', phonetic: '/e.pi.naʁ/' }, es: { name: 'Espinaca', phonetic: '/es.pi.ˈna.ka/' }, de: { name: 'Spinat', phonetic: '/ʃpiˈnaːt/' } } },

  // 水果类
  { id: 'apple', name: '苹果', category: 'fruit', categoryName: '水果', icon: '🍎', defaultUnit: '个', defaultShelfDays: 14, translations: { en: { name: 'Apple', phonetic: '/ˈæp.əl/' }, ja: { name: 'りんご', phonetic: 'リンゴ (ringo)' }, ko: { name: '사과', phonetic: '사과 (sagwa)' }, fr: { name: 'Pomme', phonetic: '/pɔm/' }, es: { name: 'Manzana', phonetic: '/man.ˈθa.na/' }, de: { name: 'Apfel', phonetic: '/ˈap.fəl/' } } },
  { id: 'banana', name: '香蕉', category: 'fruit', categoryName: '水果', icon: '🍌', defaultUnit: '根', defaultShelfDays: 5, translations: { en: { name: 'Banana', phonetic: '/bəˈnɑː.nə/' }, ja: { name: 'バナナ', phonetic: 'バナナ (banana)' }, ko: { name: '바나나', phonetic: '바나나 (banana)' }, fr: { name: 'Banane', phonetic: '/ba.nan/' }, es: { name: 'Plátano', phonetic: '/ˈpla.ta.no/' }, de: { name: 'Banane', phonetic: '/ba.ˈnaː.nə/' } } },
  { id: 'orange', name: '橙子', category: 'fruit', categoryName: '水果', icon: '🍊', defaultUnit: '个', defaultShelfDays: 14, translations: { en: { name: 'Orange', phonetic: '/ˈɒr.ɪndʒ/' }, ja: { name: 'オレンジ', phonetic: 'オレンジ (orenji)' }, ko: { name: '오렌지', phonetic: '오렌지 (orenji)' }, fr: { name: 'Orange', phonetic: '/ɔ.ʁɑ̃ʒ/' }, es: { name: 'Naranja', phonetic: '/na.ˈɾan.xa/' }, de: { name: 'Orange', phonetic: '/oˈʁaŋ.ʒə/' } } },
  { id: 'grape', name: '葡萄', category: 'fruit', categoryName: '水果', icon: '🍇', defaultUnit: '串', defaultShelfDays: 7, translations: { en: { name: 'Grape', phonetic: '/ɡreɪp/' }, ja: { name: 'ぶどう', phonetic: 'ブドウ (budō)' }, ko: { name: '포도', phonetic: '포도 (podo)' }, fr: { name: 'Raisin', phonetic: '/ʁɛ.zɛ̃/' }, es: { name: 'Uva', phonetic: '/ˈu.βa/' }, de: { name: 'Traube', phonetic: '/ˈtʁaʊ.bə/' } } },
  { id: 'strawberry', name: '草莓', category: 'fruit', categoryName: '水果', icon: '🍓', defaultUnit: '盒', defaultShelfDays: 3, translations: { en: { name: 'Strawberry', phonetic: '/ˈstrɔː.bər.i/' }, ja: { name: 'いちご', phonetic: 'イチゴ (ichigo)' }, ko: { name: '딸기', phonetic: '딸기 (ttalgi)' }, fr: { name: 'Fraise', phonetic: '/fʁɛz/' }, es: { name: 'Fresa', phonetic: '/ˈfɾe.sa/' }, de: { name: 'Erdbeere', phonetic: '/ˈeːʁt.beː.ʁə/' } } },
  { id: 'watermelon', name: '西瓜', category: 'fruit', categoryName: '水果', icon: '🍉', defaultUnit: '个', defaultShelfDays: 7, translations: { en: { name: 'Watermelon', phonetic: '/ˈwɔː.tər.mel.ən/' }, ja: { name: 'すいか', phonetic: 'スイカ (suika)' }, ko: { name: '수박', phonetic: '수박 (subak)' }, fr: { name: 'Pastèque', phonetic: '/pas.tɛk/' }, es: { name: 'Sandía', phonetic: '/san.ˈdi.a/' }, de: { name: 'Wassermelone', phonetic: '/ˈvas.ər.me.loː.nə/' } } },
  { id: 'mango', name: '芒果', category: 'fruit', categoryName: '水果', icon: '🥭', defaultUnit: '个', defaultShelfDays: 5, translations: { en: { name: 'Mango', phonetic: '/ˈmæŋ.ɡoʊ/' }, ja: { name: 'マンゴー', phonetic: 'マンゴー (mangō)' }, ko: { name: '망고', phonetic: '망고 (manggo)' }, fr: { name: 'Mangue', phonetic: '/mɑ̃ɡ/' }, es: { name: 'Mango', phonetic: '/ˈman.go/' }, de: { name: 'Mango', phonetic: '/ˈman.ɡo/' } } },
  { id: 'pear', name: '梨', category: 'fruit', categoryName: '水果', icon: '🍐', defaultUnit: '个', defaultShelfDays: 10, translations: { en: { name: 'Pear', phonetic: '/pɛər/' }, ja: { name: 'なし', phonetic: 'ナシ (nashi)' }, ko: { name: '배', phonetic: '배 (bae)' }, fr: { name: 'Poire', phonetic: '/pwaʁ/' }, es: { name: 'Pera', phonetic: '/ˈpe.ɾa/' }, de: { name: 'Birne', phonetic: '/ˈbɪʁ.nə/' } } },
  { id: 'blueberry', name: '蓝莓', category: 'fruit', categoryName: '水果', icon: '🫐', defaultUnit: '盒', defaultShelfDays: 5, translations: { en: { name: 'Blueberry', phonetic: '/ˈbluː.bər.i/' }, ja: { name: 'ブルーベリー', phonetic: 'ブルーベリー (burūberī)' }, ko: { name: '블루베리', phonetic: '블루베리 (beulluberi)' }, fr: { name: 'Myrtille', phonetic: '/miʁ.tij/' }, es: { name: 'Arándano', phonetic: '/a.ˈɾan.da.no/' }, de: { name: 'Heidelbeere', phonetic: '/ˈhaɪ.dəl.beː.ʁə/' } } },
  { id: 'peach', name: '桃子', category: 'fruit', categoryName: '水果', icon: '🍑', defaultUnit: '个', defaultShelfDays: 5, translations: { en: { name: 'Peach', phonetic: '/piːtʃ/' }, ja: { name: 'もも', phonetic: 'モモ (momo)' }, ko: { name: '복숭아', phonetic: '복숭아 (boksunga)' }, fr: { name: 'Pêche', phonetic: '/pɛʃ/' }, es: { name: 'Melocotón', phonetic: '/me.lo.ko.ˈton/' }, de: { name: 'Pfirsich', phonetic: '/ˈpfiːʁ.zɪç/' } } },

  // 肉类
  { id: 'pork', name: '猪肉', category: 'meat', categoryName: '肉类', icon: '🥩', defaultUnit: '克', defaultShelfDays: 3, translations: { en: { name: 'Pork', phonetic: '/pɔːrk/' }, ja: { name: 'ぶたにく', phonetic: 'ブタニク (butaniku)' }, ko: { name: '돼지고기', phonetic: '돼지고기 (dwaejigogi)' }, fr: { name: 'Porc', phonetic: '/pɔʁ/' }, es: { name: 'Cerdo', phonetic: '/ˈθeɾ.ðo/' }, de: { name: 'Schweinefleisch', phonetic: '/ˈʃvaɪ.nə.flaɪʃ/' } } },
  { id: 'beef', name: '牛肉', category: 'meat', categoryName: '肉类', icon: '🥩', defaultUnit: '克', defaultShelfDays: 3, translations: { en: { name: 'Beef', phonetic: '/biːf/' }, ja: { name: 'ぎゅうにく', phonetic: 'ギュウニク (gyūniku)' }, ko: { name: '소고기', phonetic: '소고기 (sogogi)' }, fr: { name: 'Boeuf', phonetic: '/bœf/' }, es: { name: 'Ternera', phonetic: '/teɾ.ˈne.ɾa/' }, de: { name: 'Rindfleisch', phonetic: '/ˈʁɪnt.flaɪʃ/' } } },
  { id: 'chicken', name: '鸡肉', category: 'meat', categoryName: '肉类', icon: '🍗', defaultUnit: '克', defaultShelfDays: 2, translations: { en: { name: 'Chicken', phonetic: '/ˈtʃɪk.ɪn/' }, ja: { name: 'とりにく', phonetic: 'トリニク (toriniku)' }, ko: { name: '닭고기', phonetic: '닭고기 (dakgogi)' }, fr: { name: 'Poulet', phonetic: '/pu.lɛ/' }, es: { name: 'Pollo', phonetic: '/ˈpo.ʎo/' }, de: { name: 'Hähnchen', phonetic: '/ˈhɛːn.çən/' } } },
  { id: 'bacon', name: '培根', category: 'meat', categoryName: '肉类', icon: '🥓', defaultUnit: '片', defaultShelfDays: 7, translations: { en: { name: 'Bacon', phonetic: '/ˈbeɪ.kən/' }, ja: { name: 'ベーコン', phonetic: 'ベーコン (bēkon)' }, ko: { name: '베이컨', phonetic: '베이컨 (beikon)' }, fr: { name: 'Bacon', phonetic: '/beɪ.kɔn/' }, es: { name: 'Tocino', phonetic: '/to.ˈθi.no/' }, de: { name: 'Speck', phonetic: '/ʃpɛk/' } } },
  { id: 'lamb', name: '羊肉', category: 'meat', categoryName: '肉类', icon: '🥩', defaultUnit: '克', defaultShelfDays: 3, translations: { en: { name: 'Lamb', phonetic: '/læm/' }, ja: { name: 'ラム', phonetic: 'ラム (ramu)' }, ko: { name: '양고기', phonetic: '양고기 (yanggogi)' }, fr: { name: 'Agneau', phonetic: '/a.ɲo/' }, es: { name: 'Cordero', phonetic: '/koɾ.ˈðe.ɾo/' }, de: { name: 'Lamm', phonetic: '/lam/' } } },

  // 海鲜类
  { id: 'fish', name: '鱼', category: 'seafood', categoryName: '海鲜', icon: '🐟', defaultUnit: '条', defaultShelfDays: 2, translations: { en: { name: 'Fish', phonetic: '/fɪʃ/' }, ja: { name: 'さかな', phonetic: 'サカナ (sakana)' }, ko: { name: '생선', phonetic: '생선 (saengseon)' }, fr: { name: 'Poisson', phonetic: '/pwa.sɔ̃/' }, es: { name: 'Pescado', phonetic: '/pes.ˈka.ðo/' }, de: { name: 'Fisch', phonetic: '/fɪʃ/' } } },
  { id: 'shrimp', name: '虾', category: 'seafood', categoryName: '海鲜', icon: '🍤', defaultUnit: '只', defaultShelfDays: 2, translations: { en: { name: 'Shrimp', phonetic: '/ʃrɪmp/' }, ja: { name: 'えび', phonetic: 'エビ (ebi)' }, ko: { name: '새우', phonetic: '새우 (saeu)' }, fr: { name: 'Crevette', phonetic: '/kʁə.vɛt/' }, es: { name: 'Gamba', phonetic: '/ˈɡam.ba/' }, de: { name: 'Garnele', phonetic: '/ɡaʁˈneː.lə/' } } },
  { id: 'salmon', name: '三文鱼', category: 'seafood', categoryName: '海鲜', icon: '🍣', defaultUnit: '克', defaultShelfDays: 2, translations: { en: { name: 'Salmon', phonetic: '/ˈsæm.ən/' }, ja: { name: 'サーモン', phonetic: 'サーモン (sāmon)' }, ko: { name: '연어', phonetic: '연어 (yeoneo)' }, fr: { name: 'Saumon', phonetic: '/so.mɔ̃/' }, es: { name: 'Salmón', phonetic: '/sal.ˈmon/' }, de: { name: 'Lachs', phonetic: '/laks/' } } },
  { id: 'crab', name: '螃蟹', category: 'seafood', categoryName: '海鲜', icon: '🦀', defaultUnit: '只', defaultShelfDays: 1, translations: { en: { name: 'Crab', phonetic: '/kræb/' }, ja: { name: 'かに', phonetic: 'カニ (kani)' }, ko: { name: '게', phonetic: '게 (ge)' }, fr: { name: 'Crabe', phonetic: '/kʁab/' }, es: { name: 'Cangrejo', phonetic: '/kaŋ.ˈɡɾe.xo/' }, de: { name: 'Krabbe', phonetic: '/ˈkʁa.bə/' } } },

  // 乳制品
  { id: 'milk', name: '牛奶', category: 'dairy', categoryName: '乳制品', icon: '🥛', defaultUnit: '盒', defaultShelfDays: 7, translations: { en: { name: 'Milk', phonetic: '/mɪlk/' }, ja: { name: 'ぎゅうにゅう', phonetic: 'ギュウニュウ (gyūnyū)' }, ko: { name: '우유', phonetic: '우유 (uyu)' }, fr: { name: 'Lait', phonetic: '/lɛ/' }, es: { name: 'Leche', phonetic: '/ˈle.tʃe/' }, de: { name: 'Milch', phonetic: '/mɪlç/' } } },
  { id: 'yogurt', name: '酸奶', category: 'dairy', categoryName: '乳制品', icon: '🍶', defaultUnit: '瓶', defaultShelfDays: 10, translations: { en: { name: 'Yogurt', phonetic: '/ˈjoʊ.ɡərt/' }, ja: { name: 'ヨーグルト', phonetic: 'ヨーグルト (yōguruto)' }, ko: { name: '요구르트', phonetic: '요구르트 (yogureuteu)' }, fr: { name: 'Yaourt', phonetic: '/ja.uʁ/' }, es: { name: 'Yogur', phonetic: '/jo.ˈɣuɾ/' }, de: { name: 'Joghurt', phonetic: '/ˈjoː.ɡʊʁt/' } } },
  { id: 'cheese', name: '奶酪', category: 'dairy', categoryName: '乳制品', icon: '🧀', defaultUnit: '块', defaultShelfDays: 14, translations: { en: { name: 'Cheese', phonetic: '/tʃiːz/' }, ja: { name: 'チーズ', phonetic: 'チーズ (chīzu)' }, ko: { name: '치즈', phonetic: '치즈 (chijeu)' }, fr: { name: 'Fromage', phonetic: '/fʁo.maʒ/' }, es: { name: 'Queso', phonetic: '/ˈke.so/' }, de: { name: 'Käse', phonetic: '/ˈkɛː.zə/' } } },
  { id: 'butter', name: '黄油', category: 'dairy', categoryName: '乳制品', icon: '🧈', defaultUnit: '块', defaultShelfDays: 30, translations: { en: { name: 'Butter', phonetic: '/ˈbʌt.ər/' }, ja: { name: 'バター', phonetic: 'バター (batā)' }, ko: { name: '버터', phonetic: '버터 (beoteo)' }, fr: { name: 'Beurre', phonetic: '/bœʁ/' }, es: { name: 'Mantequilla', phonetic: '/man.te.ˈki.ʎa/' }, de: { name: 'Butter', phonetic: '/ˈbʊt.ər/' } } },

  // 蛋类
  { id: 'egg', name: '鸡蛋', category: 'egg', categoryName: '蛋类', icon: '🥚', defaultUnit: '个', defaultShelfDays: 21, translations: { en: { name: 'Egg', phonetic: '/ɛɡ/' }, ja: { name: 'たまご', phonetic: 'タマゴ (tamago)' }, ko: { name: '달걀', phonetic: '달걀 (dalgyal)' }, fr: { name: 'Oeuf', phonetic: '/œf/' }, es: { name: 'Huevo', phonetic: '/ˈwe.βo/' }, de: { name: 'Ei', phonetic: '/aɪ/' } } },
  { id: 'duckegg', name: '鸭蛋', category: 'egg', categoryName: '蛋类', icon: '🥚', defaultUnit: '个', defaultShelfDays: 14, translations: { en: { name: 'Duck Egg', phonetic: '/dʌk ɛɡ/' }, ja: { name: 'あひるの卵', phonetic: 'アヒルノタマゴ (ahiru no tamago)' }, ko: { name: '오리알', phonetic: '오리알 (orial)' }, fr: { name: 'Oeuf de canard', phonetic: '/œf də ka.naʁ/' }, es: { name: 'Huevo de pato', phonetic: '/ˈwe.βo ðe ˈpa.to/' }, de: { name: 'Entenei', phonetic: '/ˈɛn.tən.aɪ/' } } },

  // 饮料类
  { id: 'juice', name: '果汁', category: 'drink', categoryName: '饮料', icon: '🧃', defaultUnit: '瓶', defaultShelfDays: 7, translations: { en: { name: 'Juice', phonetic: '/dʒuːs/' }, ja: { name: 'ジュース', phonetic: 'ジュース (jūsu)' }, ko: { name: '주스', phonetic: '주스 (juseu)' }, fr: { name: 'Jus', phonetic: '/ʒy/' }, es: { name: 'Zumo', phonetic: '/ˈθu.mo/' }, de: { name: 'Saft', phonetic: '/zaft/' } } },
  { id: 'beer', name: '啤酒', category: 'drink', categoryName: '饮料', icon: '🍺', defaultUnit: '罐', defaultShelfDays: 365, translations: { en: { name: 'Beer', phonetic: '/bɪər/' }, ja: { name: 'ビール', phonetic: 'ビール (bīru)' }, ko: { name: '맥주', phonetic: '맥주 (maekju)' }, fr: { name: 'Bière', phonetic: '/bjɛʁ/' }, es: { name: 'Cerveza', phonetic: '/θeɾ.ˈβe.θa/' }, de: { name: 'Bier', phonetic: '/biːɐ̯/' } } },
  { id: 'cola', name: '可乐', category: 'drink', categoryName: '饮料', icon: '🥤', defaultUnit: '瓶', defaultShelfDays: 180, translations: { en: { name: 'Cola', phonetic: '/ˈkoʊ.lə/' }, ja: { name: 'コーラ', phonetic: 'コーラ (kōra)' }, ko: { name: '콜라', phonetic: '콜라 (kolla)' }, fr: { name: 'Cola', phonetic: '/kɔ.la/' }, es: { name: 'Cola', phonetic: '/ˈko.la/' }, de: { name: 'Cola', phonetic: '/ˈkoː.la/' } } },

  // 调料类
  { id: 'ketchup', name: '番茄酱', category: 'condiment', categoryName: '调料', icon: '🍅', defaultUnit: '瓶', defaultShelfDays: 90, translations: { en: { name: 'Ketchup', phonetic: '/ˈkɛtʃ.əp/' }, ja: { name: 'ケチャップ', phonetic: 'ケチャップ (kechappu)' }, ko: { name: '케첩', phonetic: '케첩 (kecheop)' }, fr: { name: 'Ketchup', phonetic: '/kɛ.tʃœp/' }, es: { name: 'Kétchup', phonetic: '/ˈket.tʃup/' }, de: { name: 'Ketchup', phonetic: '/ˈkɛt͡ʃ.ap/' } } },
  { id: 'soysauce', name: '酱油', category: 'condiment', categoryName: '调料', icon: '🫙', defaultUnit: '瓶', defaultShelfDays: 180, translations: { en: { name: 'Soy Sauce', phonetic: '/sɔɪ sɔːs/' }, ja: { name: 'しょうゆ', phonetic: 'ショウユ (shōyu)' }, ko: { name: '간장', phonetic: '간장 (ganjang)' }, fr: { name: 'Sauce soja', phonetic: '/sos so.ʒa/' }, es: { name: 'Salsa de soja', phonetic: '/ˈsal.sa ðe ˈso.xa/' }, de: { name: 'Sojasoße', phonetic: '/ˈzoː.ja.zoː.sə/' } } },
  { id: 'mayo', name: '蛋黄酱', category: 'condiment', categoryName: '调料', icon: '🫙', defaultUnit: '瓶', defaultShelfDays: 60, translations: { en: { name: 'Mayonnaise', phonetic: '/ˌmeɪ.əˈneɪz/' }, ja: { name: 'マヨネーズ', phonetic: 'マヨネーズ (mayonēzu)' }, ko: { name: '마요네즈', phonetic: '마요네즈 (mayonejeu)' }, fr: { name: 'Mayonnaise', phonetic: '/ma.jɔ.nɛz/' }, es: { name: 'Mayonesa', phonetic: '/ma.ʝo.ˈne.sa/' }, de: { name: 'Mayonnaise', phonetic: '/ma.joˈnɛː.zə/' } } },

  // 主食类
  { id: 'bread', name: '面包', category: 'grain', categoryName: '主食', icon: '🍞', defaultUnit: '个', defaultShelfDays: 5, translations: { en: { name: 'Bread', phonetic: '/brɛd/' }, ja: { name: 'パン', phonetic: 'パン (pan)' }, ko: { name: '빵', phonetic: '빵 (ppang)' }, fr: { name: 'Pain', phonetic: '/pɛ̃/' }, es: { name: 'Pan', phonetic: '/pan/' }, de: { name: 'Brot', phonetic: '/bʁoːt/' } } },
  { id: 'tofu', name: '豆腐', category: 'grain', categoryName: '主食', icon: '🫘', defaultUnit: '块', defaultShelfDays: 5, translations: { en: { name: 'Tofu', phonetic: '/ˈtoʊ.fuː/' }, ja: { name: 'とうふ', phonetic: 'トウフ (tōfu)' }, ko: { name: '두부', phonetic: '두부 (dubu)' }, fr: { name: 'Tofu', phonetic: '/to.fu/' }, es: { name: 'Tofu', phonetic: '/ˈto.fu/' }, de: { name: 'Tofu', phonetic: '/ˈtoː.fuː/' } } },
  { id: 'noodle', name: '面条', category: 'grain', categoryName: '主食', icon: '🍜', defaultUnit: '包', defaultShelfDays: 3, translations: { en: { name: 'Noodle', phonetic: '/ˈnuː.dəl/' }, ja: { name: 'めん', phonetic: 'メン (men)' }, ko: { name: '국수', phonetic: '국수 (guksu)' }, fr: { name: 'Nouilles', phonetic: '/nuj/' }, es: { name: 'Fideos', phonetic: '/fi.ˈðe.os/' }, de: { name: 'Nudeln', phonetic: '/ˈnuː.dəln/' } } }
]

const CATEGORIES = [
  { id: 'all', name: '全部', icon: '🧊' },
  { id: 'vegetable', name: '蔬菜', icon: '🥦' },
  { id: 'fruit', name: '水果', icon: '🍎' },
  { id: 'meat', name: '肉类', icon: '🥩' },
  { id: 'seafood', name: '海鲜', icon: '🐟' },
  { id: 'dairy', name: '乳制品', icon: '🥛' },
  { id: 'egg', name: '蛋类', icon: '🥚' },
  { id: 'drink', name: '饮料', icon: '🧃' },
  { id: 'condiment', name: '调料', icon: '🫙' },
  { id: 'grain', name: '主食', icon: '🍞' }
]

const LANGUAGES = [
  { id: 'en', name: '英语', flag: '🇺🇸', ttsLang: 'en_US' },
  { id: 'ja', name: '日语', flag: '🇯🇵', ttsLang: 'ja_JP' },
  { id: 'ko', name: '韩语', flag: '🇰🇷', ttsLang: 'ko_KR' },
  { id: 'fr', name: '法语', flag: '🇫🇷', ttsLang: 'fr_FR' },
  { id: 'es', name: '西班牙语', flag: '🇪🇸', ttsLang: 'es_ES' },
  { id: 'de', name: '德语', flag: '🇩🇪', ttsLang: 'de_DE' }
]

module.exports = {
  INGREDIENTS_DB,
  CATEGORIES,
  LANGUAGES,
  getIngredientById: (id) => INGREDIENTS_DB.find(item => item.id === id),
  searchIngredients: (keyword) => {
    if (!keyword) return INGREDIENTS_DB
    const kw = keyword.toLowerCase()
    return INGREDIENTS_DB.filter(item =>
      item.name.includes(keyword) || item.id.includes(kw)
    )
  }
}
